version = 1

test_patterns = [
  "test/**",
  "**/*_test.go"
]

[[analyzers]]
name = "shell"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/sge-network/sge"

[[transformers]]
name = "gofumpt"

[[transformers]]
name = "gofmt"